name: Graal tests
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        java: ['17']
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: ${{ matrix.java }}
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: DeLaGuardo/setup-clojure@12.5
        with:
          lein: latest
          bb: latest

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: deps-${{ hashFiles('deps.edn') }}
          restore-keys: deps-

      - run: bb graal-tests
